# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-16 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strong', '0002_auto_20180316_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='strong'),
        ),
    ]
