# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-19 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import strong.models


class Migration(migrations.Migration):

    dependencies = [
        ('strong', '0005_auto_20180316_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=strong.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='images',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='strong.Project'),
        ),
    ]
